Debian package ready solution

diff --git a/ci/prepare_deb_package b/ci/prepare_deb_package
--- a/ci/prepare_deb_package
+++ b/ci/prepare_deb_package
@@ -15,32 +15,42 @@ create_evdi_deb_package()
   local temp_dir
   temp_dir=$(mktemp -d)
 
+  local repo_dir="$1"
   local deb_dir="$temp_dir/EVDI"
   local control_dir="$deb_dir/DEBIAN"
   local displaylink_dir="$deb_dir/opt/displaylink"
 
-  mkdir -p "$control_dir" "$displaylink_dir" "$deb_dir"/etc/{modules-load,modprobe}.d
+  mkdir -p \
+      "$control_dir" \
+      "$displaylink_dir" \
+      "$deb_dir/usr/src" \
+      "$deb_dir"/etc/{modules-load,modprobe}.d
 
-  local archive_path="$displaylink_dir/evdi.tar.gz"
+  (
+    cd "$repo_dir"
 
-  git archive --format tar.gz -9 --output "$archive_path" HEAD
+    git archive --format tar HEAD module | (cd "$temp_dir" && tar xf -)
 
-  if ! make -C library; then
-    echo >&2 "Failed to build evdi library"
-    rm -rf "$temp_dir"
-    return 1
-  fi
+    if ! mv "$temp_dir/module" "$deb_dir/usr/src/evdi-$evdi_version"; then
+      echo >&2 "Failed to move evdi module sources"
+      rm -rf "$temp_dir"
+      return 1
+    fi
 
-  if ! install -Dm 644 library/libevdi.so "$deb_dir/usr/lib/libevdi.so"; then
-    echo >&2 "Failed to copy evdi library"
-    rm -rf "$temp_dir"
-    return 1
-  fi
+    if ! make -C library; then
+      echo >&2 "Failed to build evdi library"
+      rm -rf "$temp_dir"
+      return 1
+    fi
+
+    if ! install -Dm 644 library/libevdi.so "$deb_dir/usr/lib/libevdi.so"; then
+      echo >&2 "Failed to copy evdi library"
+      rm -rf "$temp_dir"
+      return 1
+    fi
+  )
 
   echo 'evdi' > "$deb_dir/etc/modules-load.d/evdi.conf"
-
-  echo 'options evdi initial_device_count=4' \
-        > "$deb_dir/etc/modprobe.d/evdi.conf"
 
   cat > "$control_dir/control" << EOF
 Source: evdi
@@ -53,79 +63,45 @@ Description: $evdi_description
 Version: $evdi_version
 EOF
 
-  cat > "$control_dir/postinst" << 'EOF'
+  cat > "$control_dir/postinst" << EOF
 #!/usr/bin/env bash
 
 build_evdi()
 {
-  local archive='/opt/displaylink/evdi.tar.gz'
-  local evdi_dir="$1"
-
-  if ! tar xf "$archive" -C "$evdi_dir"; then
-    echo >&2 "Unable to extract $archive to $evdi_dir"
-    return 1
-  fi
-
+  local evdi_dir='/usr/src/evdi-$evdi_version'
   local dkms_evdi_path='/var/lib/dkms/evdi'
-  local make_log_regex="$dkms_evdi_path/[[:alnum:]./]+/make\\.log"
-  local dkms_log="$evdi_dir/dkms.log"
+  local make_log_regex="\$dkms_evdi_path/[[:alnum:]./]+/make\\\\.log"
+
+  local dkms_log
+  dkms_log=\$(mktemp) || exit 1
+
   local evdi_make_log_path
-  evdi_make_log_path="/var/log/displaylink/evdi_install_make.$(date '+%F-%H%M').log"
+  evdi_make_log_path="/var/log/displaylink/evdi_install_make.\$(date '+%F-%H%M').log"
 
-  dkms install "$evdi_dir/module" 2>&1 | tee "$dkms_log" | sed -E "s~$make_log_regex~$evdi_make_log_path~"
-  local retval=${PIPESTATUS[0]}
+  dkms install "\$evdi_dir" 2>&1 | tee "\$dkms_log" | sed -E "s~\$make_log_regex~\$evdi_make_log_path~"
+  local retval=\${PIPESTATUS[0]}
 
-  if [[ $retval == 3 ]]; then
+  if [[ \$retval == 3 ]]; then
     echo >&2 "EVDI DKMS module already installed."
 
-  elif [[ $retval != 0 ]]; then
+  elif [[ \$retval != 0 ]]; then
     echo >&2 "Failed to install evdi to the kernel tree."
-    grep -Eo "$make_log_regex" "$dkms_log" | head -n1 | xargs -r -I '{}' cp '{}' "$evdi_make_log_path"
-    make -sC "$evdi_dir/module" uninstall_dkms
-    return 1
+    grep -Eo "\$make_log_regex" "\$dkms_log" | head -n1 | xargs -r -I '{}' cp '{}' "\$evdi_make_log_path"
+    dkms remove 'evdi/$evdi_version' --all
+    rm "\$dkms_log"
+    exit 1
   fi
+
+  rm "\$dkms_log"
 }
 
-cleanup()
-{
-  [[ -d $temp_dir ]] && rm -rf "$temp_dir"
-}
-
-temp_dir=$(mktemp -d) || exit 1
-
-trap cleanup EXIT
-
-build_evdi "$temp_dir"
-cleanup
+build_evdi
 EOF
 
-  cat > "$control_dir/prerm" << 'EOF'
+  cat > "$control_dir/prerm" << EOF
 #!/usr/bin/env bash
 
-remove_evdi()
-{
-  local archive='/opt/displaylink/evdi.tar.gz'
-  local evdi_dir="$1"
-
-  if ! tar xf "$archive" -C "$evdi_dir"; then
-    echo >&2 "Unable to extract $archive to $evdi_dir"
-    return 1
-  fi
-
-  make -sC "$evdi_dir/module" uninstall_dkms
-}
-
-cleanup()
-{
-  [[ -d $temp_dir ]] && rm -rf "$temp_dir"
-}
-
-temp_dir=$(mktemp -d) || exit 1
-
-trap cleanup EXIT
-
-remove_evdi "$temp_dir"
-cleanup
+dkms remove evdi/$evdi_version --all
 EOF
 
   chmod 0755 "$control_dir"/{prerm,postinst}
@@ -140,11 +116,11 @@ EOF
   rm -rf "$temp_dir"
 }
 
-cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1
+script_dir="$(dirname "${BASH_SOURCE[0]}")"
 
-. ci/deb_config || exit 1
+. "$script_dir/deb_config" || exit 1
 
 : "${evdi_maintainer:?}" "${evdi_description:?}" "${evdi_version:?}"
 
-create_evdi_deb_package
+create_evdi_deb_package "$script_dir/.."
 
diff --git a/ci/test_deb_package b/ci/test_deb_package
--- a/ci/test_deb_package
+++ b/ci/test_deb_package
@@ -25,10 +25,11 @@ print_missing_files()
   done
 }
 
+. "$(dirname "${BASH_SOURCE[0]}")/deb_config" || exit 1
+
 files=(
-  '/opt/displaylink/evdi.tar.gz'
   '/etc/modules-load.d/evdi.conf'
-  '/etc/modprobe.d/evdi.conf'
+  "/usr/src/evdi-$evdi_version"
   '/usr/lib/libevdi.so'
 )
 
@@ -37,13 +38,18 @@ if files_exist "${files[@]}"; then
   exit 1
 fi
 
-if ! dpkg -i "$1"; then
+if ! sudo dpkg -i "$1"; then
   echo >&2 "DPKG failed to install: $1"
   exit 1
 fi
 
 if ! files_exist "${files[@]}"; then
   print_missing_files "${files[@]}"
+  exit 1
+fi
+
+if ! (modprobe evdi || modinfo evdi); then
+  echo >&2 "modprobe failed"
   exit 1
 fi
 
