Test evdi package contains correct binary for its architecture

diff --git a/ci/test_deb_package b/ci/test_deb_package
--- a/ci/test_deb_package
+++ b/ci/test_deb_package
@@ -17,6 +17,61 @@ files_exist()
   return 0
 }
 
+to_realpath()
+{
+  echo "$(cd "$(dirname "$1")"; pwd -P)/$(basename "$1")"
+}
+
+get_architecture()
+{
+  local deb="$1"
+
+  dpkg-deb --info "$deb" | grep "Architecture" |  awk -F ':' '{print $2}' | xargs
+}
+
+validate_binary_architecture()
+{
+  local arch="$1"
+  local binary="$2"
+  local binary_arch=
+
+  binary_arch=$(file "$binary" | awk -F ', ' '{print $2}')
+
+  [[ "$arch" == "amd64" ]] && [[ "$binary_arch" != "x86-64" ]] && echo "$binary architecture $binary_arch does not match $arch" && false
+  [[ "$arch" == "i386"  ]]  && [[ "$binary_arch" != "Intel 80386"  ]] && echo "$binary architecture $binary_arch does not match $arch" && false
+  [[ "$arch" == "arm64" ]] && [[ "$binary_arch" != "ARM aarch64"  ]] && echo "$binary architecture $binary_arch does not match $arch" && false
+  [[ "$arch" == "armhf" ]] && [[ "$binary_arch" != "ARM"  ]] && echo "$binary architecture $binary_arch does not match $arch" && false
+
+  true
+}
+
+inspect_deb_contents()
+{
+  local deb=$1
+  local arch=
+  local temp_dir
+  temp_dir=$(mktemp -d)
+  arch=$(get_architecture "$deb")
+
+  files=(
+    'etc/modules-load.d/evdi.conf'
+    "usr/src/evdi-$evdi_version"
+    'usr/lib/libevdi.so'
+  )
+
+  (cd "$temp_dir"
+      dpkg-deb -x "$deb" "$temp_dir"
+      for f in "${files[@]}"
+      do
+          f="$temp_dir/$f"
+          [[ -e "$f" ]] || (echo >&2 "Couldn't find file: $f" && exit 1)
+      done
+
+     validate_binary_architecture "$arch" "$temp_dir/usr/lib/libevdi.so"
+  )
+  rm -rf "$temp_dir"
+}
+
 print_missing_files()
 {
   while [[ $# -gt 0 ]]; do
@@ -24,6 +79,7 @@ print_missing_files()
     shift
   done
 }
+
 
 . "$(dirname "${BASH_SOURCE[0]}")/deb_config" || exit 1
 
@@ -53,5 +109,8 @@ if ! (modprobe evdi && modinfo evdi); then
   echo >&2 "modprobe failed"
   exit 1
 fi
+
+inspect_deb_contents "$(to_realpath "$1")"
+echo "Evdi package $1 is OK!"
 
 :
